
Total Transactions =
COUNTROWS(cleaned_transactions)

Total Fraud Cases =
CALCULATE(
    COUNTROWS(cleaned_transactions),
    cleaned_transactions[Is_Fraud] = 1
)

Fraud Rate % =
DIVIDE(
    [Total Fraud Cases],
    [Total Transactions],
    0
) * 100

Total Transaction Amount =
SUM(cleaned_transactions[Amount_INR])

Fraud Amount =
CALCULATE(
    SUM(cleaned_transactions[Amount_INR]),
    cleaned_transactions[Is_Fraud] = 1
)

Average Fraud Amount =
CALCULATE(
    AVERAGE(cleaned_transactions[Amount_INR]),
    cleaned_transactions[Is_Fraud] = 1
)

-- =========================================
-- BANK ANALYSIS
-- =========================================

Bank Fraud Rate % =
DIVIDE(
    CALCULATE(
        COUNTROWS(cleaned_transactions),
        cleaned_transactions[Is_Fraud] = 1
    ),
    COUNTROWS(cleaned_transactions),
    0
) * 100

Top Fraud Bank Rank =
RANKX(
    ALL(cleaned_transactions[Sender_Bank]),
    [Total Fraud Cases],
    ,
    DESC
)

-- =========================================
-- STATE ANALYSIS
-- =========================================

State Fraud Rate % =
DIVIDE(
    CALCULATE(
        COUNTROWS(cleaned_transactions),
        cleaned_transactions[Is_Fraud] = 1
    ),
    COUNTROWS(cleaned_transactions),
    0
) * 100

Cross State Fraud Count =
CALCULATE(
    COUNTROWS(cleaned_transactions),
    cleaned_transactions[Is_Fraud] = 1,
    cleaned_transactions[Cross_State_Txn] = 1
)

-- =========================================
-- TIME ANALYSIS
-- =========================================

Night Fraud Count =
CALCULATE(
    COUNTROWS(cleaned_transactions),
    cleaned_transactions[Is_Fraud] = 1,
    cleaned_transactions[Is_Night_Txn] = 1
)

Weekend Fraud Count =
CALCULATE(
    COUNTROWS(cleaned_transactions),
    cleaned_transactions[Is_Fraud] = 1,
    cleaned_transactions[Is_Weekend] = 1
)

-- =========================================
-- RISK ANALYSIS
-- =========================================

High Risk Transactions =
CALCULATE(
    COUNTROWS(cleaned_transactions),
    cleaned_transactions[Risk_Score] >= 75
)

Average Risk Score =
AVERAGE(cleaned_transactions[Risk_Score])

-- =========================================
-- APP ANALYSIS
-- =========================================

UPI App Fraud Rate % =
DIVIDE(
    CALCULATE(
        COUNTROWS(cleaned_transactions),
        cleaned_transactions[Is_Fraud] = 1
    ),
    COUNTROWS(cleaned_transactions),
    0
) * 100
